version: '3.8'

services:

  style-bert-vits2-api:
    build: 
      context: .
      dockerfile: Style-Bert-VITS2/Dockerfile.external

    volumes:
      - ./Style-Bert-VITS2:/app
      - ./Style-Bert-VITS2/model_assets:/model_assets
      - ./Style-Bert-VITS2/Data:/Data

    ports:
      - "8000:8000"
      - "5000:5000"
    tty: true
    working_dir: /app
    command: >
      sh -c "python initialize.py && 
             python server_fastapi.py"

  ron-j:
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./.cache:/root/.cache
      - ./.streamlit:/root/.streamlit
    environment:
      - PULSE_SERVER=/mnt/wslg/PulseServer
      - DISPLAY=$DISPLAY
      # - PULSE_SERVER=$PULSE_SERVER
      - WAYLAND_DISPLAY=$WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR
    ports:
      - 8502:8502
      - 8503:8503
    env_file:
      - .env
    working_dir: /app
    tty: true
    command: streamlit run streamlit/main.py --server.port 8502
    # network_mode: "host"

